// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7b9mxgsYd6p6bheLkGnVpFfZhLIYh1So',
    appId: '1:73371540080:web:895f21f1f0ae4c521172b5',
    messagingSenderId: '73371540080',
    projectId: 'safetyjacket4iot',
    authDomain: 'safetyjacket4iot.firebaseapp.com',
    databaseURL: 'https://safetyjacket4iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safetyjacket4iot.firebasestorage.app',
    measurementId: 'G-KBYLE1NJ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NBqdHMlbpxtsjDgwEnljXmGqhgAI4cA',
    appId: '1:73371540080:android:5b7e5e26aa0052471172b5',
    messagingSenderId: '73371540080',
    projectId: 'safetyjacket4iot',
    databaseURL: 'https://safetyjacket4iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safetyjacket4iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEyziofpn4G_uH1EtnDHAN1WrHUVR2fjE',
    appId: '1:73371540080:ios:86943e1f2a1daf061172b5',
    messagingSenderId: '73371540080',
    projectId: 'safetyjacket4iot',
    databaseURL: 'https://safetyjacket4iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safetyjacket4iot.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyJacket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEyziofpn4G_uH1EtnDHAN1WrHUVR2fjE',
    appId: '1:73371540080:ios:86943e1f2a1daf061172b5',
    messagingSenderId: '73371540080',
    projectId: 'safetyjacket4iot',
    databaseURL: 'https://safetyjacket4iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safetyjacket4iot.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyJacket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7b9mxgsYd6p6bheLkGnVpFfZhLIYh1So',
    appId: '1:73371540080:web:c33f2abb59aa56ee1172b5',
    messagingSenderId: '73371540080',
    projectId: 'safetyjacket4iot',
    authDomain: 'safetyjacket4iot.firebaseapp.com',
    databaseURL: 'https://safetyjacket4iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safetyjacket4iot.firebasestorage.app',
    measurementId: 'G-HPV4CNHSGP',
  );
}
